#!/usr/bin/python3
from subprocess import call
import os
f1 = open('productpage_dockerfile','w')
f1.write('FROM python:3.7.7-slim\n')
f1.write('EXPOSE 9080\n')
f1.write('COPY . .\n')
f1.write('RUN pip3 install -r practica_creativa2/bookinfo/src/productpage/requirements.txt\n')
f1.write('CMD ["python3","practica_creativa2/bookinfo/src/productpage/productpage.py","9080"]\n')
f1.close()
f2 = open('details_dockerfile','w')
f2.write('FROM ruby:2.7.1-slim\n')
f2.write('EXPOSE 9080\n')
f2.write('COPY . .\n')
f2.write('WORKDIR /opt/microservices\n')
f2.write('COPY practica_creativa2/bookinfo/src/details/details.rb /opt/microservices\n')
f2.write('ARG service_versions\n')
f2.write('ARG enable_external_book_service\n')
f2.write('ENV SERVICE_VERSION ${service_version:-v1}\n')
f2.write('ENV ENABLE_EXTERNAL_BOOK_SERVICE ${enable_external_book_service:-true}\n')
f2.write('CMD ["ruby","details.rb","9080"]\n')
f2.close()
f3 = open('ratings_dockerfile','w')
f3.write('FROM node:12.18.1-slim\n')
f3.write('EXPOSE 9080\n')
f3.write('WORKDIR /opt/microservices\n')
f3.write('COPY practica_creativa2/bookinfo/src/ratings/package.json .\n')
f3.write('COPY practica_creativa2/bookinfo/src/ratings/ratings.js .\n')
f3.write('ARG service_version\n')
f3.write('ENV SERVICE_VERSION ${service_version:-v1}\n')
f3.write('RUN npm install\n')
f3.write('CMD ["node","ratings.js","9080"]\n')
f3.close()
f4 = open('docker-compose.yml','w')
f4.write("version: '3'\n")
f4.write('services:\n')
f4.write(' productpage:\n')
f4.write("  container_name: '22-productpage'\n")
f4.write('  build:\n') 
f4.write('   context: .\n')
f4.write('   dockerfile: productpage_dockerfile\n')
f4.write('  image: 22/productpage\n')
f4.write('  ports:\n')
f4.write("   - '9080:9080'\n")
f4.write(' details:\n')
f4.write("  container_name: '22-details'\n")
f4.write('  build:\n') 
f4.write('   context: .\n')
f4.write('   dockerfile: details_dockerfile\n')              
f4.write('  image: 22/details\n')
f4.write('  ports:\n')
f4.write("   - '9080'\n")
f4.write(' reviews:\n')
f4.write("  container_name: '22-reviews'\n")
f4.write('  build: practica_creativa2/bookinfo/src/reviews/reviews-wlpcfg\n')
f4.write('  image: 22/reviews\n')
f4.write('  ports:\n')
f4.write("   - '9080'\n")
f4.write('  links:\n')
f4.write('   - ratings\n')
f4.write('  environment:\n')
f4.write('   - ENABLE_RATINGS=true\n')
f4.write(' ratings:\n')
f4.write("  container_name: '22-ratings'\n")
f4.write('  build:\n') 
f4.write('   context: .\n')
f4.write('   dockerfile: ratings_dockerfile\n')
f4.write('  image: 22/ratings\n')
f4.write('  ports:\n')
f4.write("   - '9080'\n")
f4.close()
os.chdir(r'/home/dani22sanz03/practica_creativa2/bookinfo/src/reviews')
call(['sudo docker run --rm -u root -v "$(pwd)":/home/gradle/project -w /home/gradle/project gradle:4.8.1 gradle clean build'],shell=True)
os.chdir(r'/home/dani22sanz03')
call(['sudo docker-compose build'],shell=True)
call(['sudo docker-compose up'],shell=True)